// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Swagger user management service - OpenAPI 3.0
 *
 * This is a sample User management server based on the OpenAPI 3.0 specification.
 *
 * API version: 1.0.0
 */

package openapi

type UserRole struct {
	UserId string `json:"userId,omitempty"`

	RoleId string `json:"roleId,omitempty"`

	Active bool `json:"active,omitempty"`
}

// AssertUserRoleRequired checks if the required fields are not zero-ed
func AssertUserRoleRequired(obj UserRole) error {
	return nil
}

// AssertUserRoleConstraints checks if the values respects the defined constraints
func AssertUserRoleConstraints(obj UserRole) error {
	return nil
}
