// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Swagger user management service - OpenAPI 3.0
 *
 * This is a sample User management server based on the OpenAPI 3.0 specification.
 *
 * API version: 1.0.0
 */

package openapi

type UserGroups struct {
	Id string `json:"id,omitempty"`

	Name string `json:"name,omitempty"`

	RoleId string `json:"roleId,omitempty"`

	UserId string `json:"userId,omitempty"`

	IsActive bool `json:"isActive,omitempty"`

	IsDeleted bool `json:"isDeleted,omitempty"`
}

// AssertUserGroupsRequired checks if the required fields are not zero-ed
func AssertUserGroupsRequired(obj UserGroups) error {
	return nil
}

// AssertUserGroupsConstraints checks if the values respects the defined constraints
func AssertUserGroupsConstraints(obj UserGroups) error {
	return nil
}
