// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Swagger user management service - OpenAPI 3.0
 *
 * This is a sample User management server based on the OpenAPI 3.0 specification.
 *
 * API version: 1.0.0
 */

package openapi

type User struct {
	Id string `json:"Id,omitempty"`

	UserName string `json:"UserName,omitempty"`

	FirstName string `json:"FirstName,omitempty"`

	LastName string `json:"LastName,omitempty"`

	FullName string `json:"FullName,omitempty"`

	Email string `json:"Email,omitempty"`

	UserGroupId int64 `json:"UserGroupId,omitempty"`

	Active bool `json:"Active,omitempty"`

	Deleted bool `json:"Deleted,omitempty"`
}

// AssertUserRequired checks if the required fields are not zero-ed
func AssertUserRequired(obj User) error {
	return nil
}

// AssertUserConstraints checks if the values respects the defined constraints
func AssertUserConstraints(obj User) error {
	return nil
}
