// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Swagger user management service - OpenAPI 3.0
 *
 * This is a sample User management server based on the OpenAPI 3.0 specification.
 *
 * API version: 1.0.0
 */

package main

import (
	openapi2 "github.com/donskova1ex/usermanagement/openapi"
	"log"
	"net/http"
)

func main() {
	log.Printf("Server started")

	PersonsAPIService := openapi2.NewPersonsAPIService()
	PersonsAPIController := openapi2.NewPersonsAPIController(PersonsAPIService)

	RolesAPIService := openapi2.NewRolesAPIService()
	RolesAPIController := openapi2.NewRolesAPIController(RolesAPIService)

	UserGroupsAPIService := openapi2.NewUserGroupsAPIService()
	UserGroupsAPIController := openapi2.NewUserGroupsAPIController(UserGroupsAPIService)

	UserRolesAPIService := openapi2.NewUserRolesAPIService()
	UserRolesAPIController := openapi2.NewUserRolesAPIController(UserRolesAPIService)

	UsersAPIService := openapi2.NewUsersAPIService()
	UsersAPIController := openapi2.NewUsersAPIController(UsersAPIService)

	router := openapi2.NewRouter(PersonsAPIController, RolesAPIController, UserGroupsAPIController, UserRolesAPIController, UsersAPIController)

	log.Fatal(http.ListenAndServe(":8080", router))
}
