// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Swagger user management service - OpenAPI 3.0
 *
 * This is a sample User management server based on the OpenAPI 3.0 specification.
 *
 * API version: 1.0.0
 */

package main

import (
	"log"
	"net/http"

	openapi "github.com/GIT_USER_ID/GIT_REPO_ID/openapi"
)

func main() {
	log.Printf("Server started")

	RolesAPIService := openapi.NewRolesAPIService()
	RolesAPIController := openapi.NewRolesAPIController(RolesAPIService)

	UserRolesAPIService := openapi.NewUserRolesAPIService()
	UserRolesAPIController := openapi.NewUserRolesAPIController(UserRolesAPIService)

	UsersAPIService := openapi.NewUsersAPIService()
	UsersAPIController := openapi.NewUsersAPIController(UsersAPIService)

	router := openapi.NewRouter(RolesAPIController, UserRolesAPIController, UsersAPIController)

	log.Fatal(http.ListenAndServe(":8080", router))
}
